### ISSUE TITLE
Bug - `default rules must use = operator (not := operator)`

### ISSUE THREAD

**Issue by RmStorm** [kitagry/regols#60]
Hey! Thanks for putting in the effort to make a language server for rego! Really cool! this issue in the opa repo didn't have me hopeful :sweat_smile: https://github.com/open-policy-agent/opa/issues/4041 haha.

I installed `regols` and am using it but I think I ran into a bug. I have a line in one of my policies like this:
```rego
default allow := false
```
But the language server marks it as a diagnostic error with the message:
`default rules must use = operator (not := operator)`

However, in the example [here](https://www.openpolicyagent.org/docs/latest/#logical-or) the OPA people clearly use a `:=` to define a default variable. Can this be fixed? Or am I misunderstanding something? Also happy to submit a PR if you point me in the right direction! I've never done any work on an LSP before so I'm kinda out of my depth.

**Comment by kitagry** [comment]
@RmStorm Thank you for the nice issue! Could you try https://github.com/kitagry/regols/releases/tag/v0.2.1?

**Comment by RmStorm** [comment]
Wow that was incredibly quick! It's fixed :pray: Thanks a lot :smile:
