### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alias-dev** [kitagry/regols#65]
Hi @kitagry,

Thanks for creating this! I'd like to add it to [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs), but I see there's not currently a license in this project. Would you be OK with adding one to enable distribution?

**Comment by kitagry** [comment]
I added MIT license. #66 

> Would you be OK with adding one to enable distribution?

It sounds good! Thank you!

**Comment by alias-dev** [comment]
Perfect, thank you very much! I've opened a [PR](https://github.com/NixOS/nixpkgs/pull/230297)
